### PR TITLE
Implementing Tests

### PR DESCRIPTION
**Pull request by juniorb2ss**
Creating tests.

- Add ext-bcmath to require.

### CODE REVIEW

**Comment by jpmurray** [comment]
Wow, thank you for that! I'll be looking into this (probably) tomorrow and merge it after... And will definitely plug scrutinizer and styleci right after!

**Comment by juniorb2ss** [comment]
@jpmurray :+1: I'm gladly to help

**Comment by juniorb2ss** [comment]
@jpmurray 

screenshot from 2017-08-01 11-07-34

:top:

**Comment by jpmurray** [comment]
@juniorb2ss anything you have added you feel should warrant a major version change? If it where only for the tests, I'd push a minor version for it, but I've seen you've poked around other parts too, so, just to make sure: there is no breaking changes in here?

(**edit** : juste enabled some continuous integration tools, but they won't appear into existing PR it seems. Oh well...)

**Comment by juniorb2ss** [comment]
@jpmurray 

I do not think I need a major version changes, no functionality the part was added, just refactored some parts and added tests.

**Comment by jpmurray** [comment]
Excellent. Will be merging this, let the test run on the develop branch and if everything is good, will push a minor version. Thanks again!

**Pull request merged**
